# Allow SeldonDeployment read/write access for seldon-deploy-reader/writer roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-seldon-deploy-manager
  namespace: {{ .Values.serviceConfigs.M2S_SELDON_DEPLOYMENT_NS }}
rules:
- apiGroups: ["machinelearning.seldon.io"]
  resources: ["seldondeployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-seldon-secrets-manager
  namespace: {{ .Values.serviceConfigs.M2S_SELDON_DEPLOYMENT_NS }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
