name: CD

on:
  release:
    types: [published]


jobs:

  trigger_image_publish:
    name: Trigger image publish
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - name: Help
      run: |
        echo This step is needed in order to trigger Publish Image workflow as it can only run when another workflow completes.
